# Configuration for the operator
# For available options, see python/perftest/config.py
config:
  defaultImagePrefix: ghcr.io/nscaledev/kube-perftest-

# The operator image to use
image:
  repository: ghcr.io/nscaledev/kube-perftest-controller
  pullPolicy: IfNotPresent
  tag: ""  # Defaults to appVersion

imagePullSecrets: []

# Pod-level security context
podSecurityContext:
  runAsNonRoot: true

# Container-level security context
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true

# Resources for the perftest operator pod
resources: {}

# Scheduling parameters for the perftest operator pod
nodeSelector: {}
tolerations: []
affinity: {}
