apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "iperf.fullname" . }}-client
  labels:
    {{- include "iperf.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  selector:
    matchLabels:
      {{- include "iperf.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: client
  template:
    metadata:
      {{- with .Values.client.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "iperf.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: client
    spec:
      securityContext:
        {{- toYaml .Values.client.podSecurityContext | nindent 8 }}
      # Use an init container to execute the actual work
      # That way, we know the job is complete when the daemonset becomes ready
      initContainers:
        - name: iperf-client
          securityContext:
            {{- toYaml .Values.client.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --client
            - {{ include "iperf.fullname" . }}-server
            {{- with .Values.client.args }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.client.resources | nindent 12 }}
      containers:
        - name: pause
          securityContext:
            {{- toYaml .Values.client.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - bash
            - -c
            - "sleep infinity"
          resources:
            {{- toYaml .Values.client.resources | nindent 12 }}
      affinity:
        # Schedule the client on a different node to the server
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - {{ include "iperf.name" . }}
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - {{ .Release.Name }}
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                      - server
              topologyKey: "kubernetes.io/hostname"
      {{- with .Values.client.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.client.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
