apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-perftest.fullname" . }}
  labels: {{ include "kube-perftest.labels" . | nindent 4 }}
rules:
  # Manipulating CRDs (only allow patching of our own CRDs)
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
      - get
      - watch
      - create
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    resourceNames:
      - benchmarksets.perftest.nscale.com
      - iperfs.perftest.nscale.com
      - rdmabandwidths.perftest.nscale.com
      - rdmalatencies.perftest.nscale.com
    verbs:
      - update
      - patch
  # Manipulating benchmark resources
  - apiGroups:
      - perftest.nscale.com
    resources:
      - "*"
    verbs:
      - "*"
  # Manipulating jobsets
  - apiGroups:
      - jobset.x-k8s.io
    resources:
      - jobsets
    verbs:
      - "*"
  # For the priority class scheduling strategy
  - apiGroups:
      - scheduling.k8s.io
    resources:
      - priorityclasses
    verbs:
      - "*"
  # Reading pod info
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - list
      - watch
      - get
