apiVersion: perftest.stackhpc.com/v1alpha1
kind: BenchmarkSet
metadata:
  name: openfoam-cni
spec:
  template:
    apiVersion: perftest.stackhpc.com/v1alpha1
    kind: OpenFOAM
    spec:
      imagePullPolicy: Always
      hostNetwork: false
      transport: TCP
      problemSize: S
      numProcs: 48
  permutations:
    product:
      numNodes: [2, 4, 8, 12, 16, 24, 48]
