apiVersion: perftest.stackhpc.com/v1alpha1
kind: RDMABandwidth
metadata:
  generateName: rdma-bandwidth-macvlan-
spec:
  imagePullPolicy: Always
  hostNetwork: false
  networkName: default/shared-network
  resources:
    limits:
      rdma/rdma_shared_device_a: 1
  mode: write
  qps: 512
  iterations: 25
  extraArgs:
    - --tclass=96
