apiVersion: perftest.stackhpc.com/v1alpha1
kind: BenchmarkSet
metadata:
  name: iperf
spec:
  template:
    apiVersion: perftest.stackhpc.com/v1alpha1
    kind: IPerf
    spec:
      imagePullPolicy: Always
      duration: 30
  permutations:
    hostNetwork: [true, false]
    serverService: [true, false]
    streams: [1, 2, 4, 8, 16]
