apiVersion: perftest.stackhpc.com/v1alpha1
kind: BenchmarkSet
metadata:
  name: openfoam
spec:
  template:
    apiVersion: perftest.stackhpc.com/v1alpha1
    kind: OpenFOAM
    spec:
      imagePullPolicy: Always
      numProcs: 48
      problemSize: S
  permutations:
    # Produce a matrix of jobs with hostNetwork=false
    product:
      hostNetwork: [false]
      numNodes: [2, 4, 8, 12, 16, 24, 48]
    # Produce an explcit job for hostNetwork=true
    explicit:
      - hostNetwork: true
        numNodes: 2
