apiVersion: perftest.stackhpc.com/v1alpha1
kind: BenchmarkSet
metadata:
  name: openfoam
spec:
  template:
    apiVersion: perftest.stackhpc.com/v1alpha1
    kind: OpenFOAM
    metadata:
      name: openfoam
    spec:
      imagePullPolicy: Always
  permutations:
    explicit:
      - hostNetwork: false
        numProcs: 48
        numWorkers: 2
      - hostNetwork: false
        numProcs: 48
        numWorkers: 4
      - hostNetwork: false
        numProcs: 48
        numWorkers: 8
      - hostNetwork: false
        numProcs: 48
        numWorkers: 16
      - hostNetwork: false
        numProcs: 48
        numWorkers: 24
      - hostNetwork: false
        numProcs: 48
        numWorkers: 48
      - hostNetwork: true
        numProcs: 48
        numWorkers: 2
