apiVersion: perftest.stackhpc.com/v1alpha1
kind: BenchmarkSet
metadata:
  name: openfoam
spec:
  template:
    apiVersion: perftest.stackhpc.com/v1alpha1
    kind: OpenFOAM
    metadata:
      name: openfoam
    spec:
      imagePullPolicy: Always
      numProcs: 48
  permutations:
    # Produce a matrix of jobs with hostNetwork=false
    product:
      hostNetwork: [false]
      problemSize: [S, M]
      numWorkers: [2, 4, 8, 12, 16, 24, 48]
    # Produce an explcit job for each problem size for hostNetwork=true
    explicit:
      - hostNetwork: true
        problemSize: S
        numWorkers: 2
      - hostNetwork: true
        problemSize: M
        numWorkers: 2
