apiVersion: batch/v1
kind: Job
metadata:
  name: {{ name }}-iperf-client
  labels:
    {{ subresource_labels(name, 'client') | indent(4) }}
spec:
  template:
    metadata:
      labels:
        {{ subresource_labels(name, 'client') | indent(8) }}
    spec:
      {%- if spec.hostNetwork %}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {%- endif %}
      restartPolicy: Never
      containers:
        - name: iperf-client
          image: {{ spec.image }}
          imagePullPolicy: {{ spec.imagePullPolicy }}
          args:
            - --client
            - {{ name }}-iperf-server
            - --time
            - "{{ spec.duration }}"
            - --parallel
            - "{{ spec.streams }}"
      # Because these jobs are very performance sensitive, prevent the pod
      # from being scheduled onto a node that already has an iperf component running
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  {{ match_expressions() | indent(18) }}
              topologyKey: "kubernetes.io/hostname"
      {%- if spec.nodeSelector %}
      nodeSelector:
        {{ spec.nodeSelector | tojson }}
      {%- endif %}
      {%- if spec.tolerations %}
      tolerations:
        {{ spec.tolerations | tojson }}
      {%- endif %}
