apiVersion: v1
kind: Service
metadata:
  name: {{ name }}-iperf-server
  labels:
    {{ subresource_labels(name, 'server') | indent(4) }}
spec:
  ports:
    - port: 5201
      targetPort: iperf-server
      protocol: TCP
  selector:
    {{ subresource_labels(name, 'server') | indent(4) }}
