apiVersion: perftest.stackhpc.com/v1alpha1
kind: BenchmarkSet
metadata:
  name: fio-rook-nfs
spec:
  template:
    apiVersion: perftest.stackhpc.com/v1alpha1
    kind: Fio
    spec:
      direct: 1
      imagePullPolicy: Always
      iodepth: 8
      ioengine: libaio
      nrfiles: 1
      numWorkers: 1
      percentageRandom: 100
      runtime: 10s
      rw: read
      rwmixread: 50
      size: 100M
      thread: false
      hostNetwork: false
      volumeClaimTemplate:
        storageClassName: rook-nfs-share1
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 50Gi
  permutations:
    product:
      numJobs: [2,4]
      rw: ['read', "write", "randrw", "rw,readwrite"]
      bs: ['32k', '1M', '4M']
