apiVersion: perftest.stackhpc.com/v1alpha1
kind: BenchmarkSet
metadata:
  name: fio-local-path
spec:
  template:
    apiVersion: perftest.stackhpc.com/v1alpha1
    kind: Fio
    spec:
      direct: 1
      imagePullPolicy: Always
      iodepth: 8
      ioengine: libaio
      nrfiles: 1
      numWorkers: 1
      percentageRandom: 100
      runtime: 10s
      rw: read
      rwmixread: 50
      size: 1G
      thread: false
      hostNetwork: false
      volumeClaimTemplate:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  permutations:
    product:
      numJobs: [2,4]
      rw: ['read', "write", "randrw", "rw,readwrite"]
      bs: ['32k', '1M', '4M']
