apiVersion: perftest.stackhpc.com/v1alpha1
kind: BenchmarkSet
metadata:
  name: mpi-pingpong-sriov
spec:
  template:
    apiVersion: perftest.stackhpc.com/v1alpha1
    kind: MPIPingPong
    spec:
      imagePullPolicy: Always
      hostNetwork: false
      networkName: default/mlnx-net
      resources:
        limits:
          nvidia.com/mlnxnet: 1
      maxlog: 25
  repetitions: 5
  permutations:
    product:
      transport: [TCP, RDMA]
