apiVersion: perftest.stackhpc.com/v1alpha1
kind: BenchmarkSet
metadata:
  name: openfoam-sriov
spec:
  template:
    apiVersion: perftest.stackhpc.com/v1alpha1
    kind: OpenFOAM
    spec:
      imagePullPolicy: Always
      hostNetwork: false
      networkName: default/mlnx-net
      resources:
        limits:
          nvidia.com/mlnxnet: 1
      problemSize: S
      numProcs: 48
  permutations:
    product:
      transport: [TCP, RDMA]
      numNodes: [2, 4, 8, 12]
