apiVersion: perftest.stackhpc.com/v1alpha1
kind: BenchmarkSet
metadata:
  name: rdma-latency-sriov
spec:
  template:
    apiVersion: perftest.stackhpc.com/v1alpha1
    kind: RDMALatency
    spec:
      imagePullPolicy: Always
      hostNetwork: false
      networkName: default/mlnx-net
      resources:
        limits:
          nvidia.com/mlnxnet: 1
      iterations: 1000
      extraArgs:
        - --tclass=96
  permutations:
    product:
      mode: [read, write]
