apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: fiosets.perftest.stackhpc.com
spec:
  group: perftest.stackhpc.com
  scope: Namespaced
  names:
    plural: fiosets
    kind: FioSet
  versions:
    - name: v1alpha1
      deprecated: false
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                  default: ghcr.io/stackhpc/fio:main
                imagePullPolicy:
                  type: string
                  enum: [IfNotPresent, Always, Never]
                  default: IfNotPresent
                hostNetwork:
                  type: boolean
                  default: false
                runtime:
                  type: integer
                  default: 30
                filesize:
                  type: string
                  default: 1g
                clients:
                  type: array
                  default: [1]
                  items:
                    type: integer
                modes:
                  type: array
                  default: [read]
                  items:
                    type: string
                    enum: [read, randread, write, randwrite]
                blocksizes:
                  type: array
                  default: [4096]
                  items:
                    type: integer
                resources:
                  type: object
                  properties:
                    limits:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    requests:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                podSecurityContext:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                volumeClaimName:
                  type: string
                volumeClaimTemplate:
                  type: object
                  required: [spec]
                  properties:
                    metadata:
                      type: object
                      properties:
                        labels:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                        annotations:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true                  
                    spec:
                      type: object
                      required: [resources]
                      properties:
                        resources:
                          type: object
                          required: [requests]
                          properties:
                            requests:
                              type: object
                              required: [storage]
                              properties:
                                storage:
                                  type: string
                        storageClassName:
                          type: string
                        volumeName:
                          type: string
                        selector:
                          type: object
                          properties:
                            matchLabels:
                              type: object
                              x-kubernetes-preserve-unknown-fields: true
                            matchExpressions:
                              type: array
                              items:
                                x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              default: {}
              properties:
                finishedAt:
                  type: string
                count:
                  type: integer
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      clients:
                        type: integer
                      mode:
                        type: string
                        enum: [read, randread, write, randwrite]
                      blocksize:
                        type: integer
                completed:
                  type: array
                  items:
                    type: string
                succeeded:
                  type: integer
                failed:
                  type: integer
      additionalPrinterColumns:
        - name: Count
          type: integer
          jsonPath: .status.count
        - name: Succeeded
          type: integer
          jsonPath: .status.succeeded
        - name: Failed
          type: integer
          jsonPath: .status.failed
        - name: Created
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: Finished
          type: date
          jsonPath: .status.finishedAt
