apiVersion: perftest.stackhpc.com/v1alpha1
kind: BenchmarkSet
metadata:
  name: mpi-pingpong-hostnet
spec:
  template:
    apiVersion: perftest.stackhpc.com/v1alpha1
    kind: MPIPingPong
    spec:
      imagePullPolicy: Always
      hostNetwork: true
      transport: TCP
      maxlog: 25
  repetitions: 5
