name: Publish benchmark images
# Run the tasks on every push that changes the images and tags
on:
  push:
    # Note that the paths filter is not evaluated for tags, so this should run for
    # every push to a branch that changes the images and every tag
    branches: ['**']
    tags: ['**']
    paths:
      - .github/workflows/publish-benchmark-images.yaml
      - 'images/**'
jobs:
  build_push_images:
    name: Build and push benchmark images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - component: fio
          - component: iperf
          - component: perftest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate metadata for image
        id: image-meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/stackhpc/${{ matrix.component }}
          # Produce the branch name or tag and the SHA as tags
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=

      - name: Build and push image
        uses: stackhpc/github-actions/docker-multiarch-build-push@master
        with:
          cache-key: ${{ matrix.component }}
          context: ./images/${{ matrix.component }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.image-meta.outputs.tags }}
          labels: ${{ steps.image-meta.outputs.labels }}
